services:
  borgpull:
    build:
      context: .
    restart: always
    image: workleast/borgpull
    container_name: borgpull
    volumes:
      - path/to/repository:/backups # replace with your actual path to repository directory here
      - ./config/ssh/id_rsa:/root/.ssh/id_rsa
      - ./config/crontab.txt:/etc/crontabs/root
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      BACKUP_ADDR: "user@server_ip" # replace with your actual backup server's address here
      ARCHIVE_NAME: "archive-{now:%Y-%m-%dT%H:%M:%S}"
      TARGET_DIR: "/" # replace with your target directory (to be backed up) in the backup server
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
